### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by HalfSweet** [chenxuuu/image2display#1]
# 功能

可以将图片根据一定的设定方式转化为对应的c数组/bin文件的图像取模软件

## 支持多灰度

* [x] 可以将图片转化为单色/4灰度/16灰度格式
* [x] 也支持8灰度（3bit）/32灰度（5bit）格式（跨个多个字节来表示）

## 支持各种抖动算法

* [x] 支持误差扩散，蓝噪声等多种抖动算法
* [x] 且同时支持多灰度转化，以获得最佳显示效果

## 支持多种图片格式

* [x] 支持主流的图片格式转化，如jpg、png、bmp等
* [ ] gif可以转化为多帧图片（误

## 支持对转换后的图片进行一些简单修改

* [x] 裁剪
* [ ] 增加空白等

## 支持自定义文件头

* [x] 在导出的数据头部加入分辨率、灰度等级等信息，方便后期处理
* [ ] 如果是是c文件的形式导出，可以选择使用硬编码的文件头或者使用使用结构体来保存所需的数据

## 支持多种格式导出

* [ ] 可以支持典型以c数组/二进制文件的方式进行导出转换后的图片

## 支持转换后的文件重新转换为图片并以图片的格式保存

* [ ] 可以在转换为二进制或者c数组之后的文件重新转换为图片，可以预览并保存为jpg/png等格式。并且转换的参数可以读取文件头/注释等方式获取，或者由用户通过GUI进行设置。

**Comment by chenxuuu** [comment]
Image2Lcd的功能截图，留做参考

![图片](https://github.com/chenxuuu/image2display/assets/10357394/82ab7543-60fd-4189-a397-c04779a38599)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/fb674baa-8f2a-4db1-8dd2-6158f28f04fe)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/5ede032c-f83a-4c8e-bf20-3ae57b5c84e5)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/b1bf5058-8189-4575-98dd-ea8c26d87bd0)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/cc7528ff-41de-4841-99d0-cf098ed76e93)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/c56d9f0e-197c-445b-ae12-c90f6b82692b)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/0bbed8d5-a81c-4773-a601-1767e8c20ed4)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/86c14b5d-1fbc-4292-8611-5703d5eecb2d)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/616ddede-b274-402a-943d-649a671f7b96)
![图片](https://github.com/chenxuuu/image2display/assets/10357394/0c584e25-acc7-4e74-bf9a-776a9fd9a6de)

**Comment by chenxuuu** [comment]
![图片](https://github.com/user-attachments/assets/f6e5b24d-f4eb-4ff7-b22c-1158096ab234)

pctolcd2022的截图，存档用

**Comment by chenxuuu** [comment]
字体取模大致功能

- 占用尺寸
  - 宽度、高度
- 字体尺寸
  - 字号大小
- 字体偏移量
  - x、y
- 颜色，只支持单色
  - 二值化需要提供阈值
  - 灰度：2位、4位、8位
- 反色
  - 可设置黑白反色
- 取模方式
  - 一共n种，参考图像取模
- 高低位优先
  - 选择高位优先或低位优先

- 字符集
  - 手动指定特定字符
  - 预置字符集：中英文符号、英文字母、一级字库、二级字库
  - 自定义unicode编码范围

- 压缩
  - 无压缩
  - RLE压缩，提供demo
  - 待定

**Comment by chenxuuu** [comment]
字体取模UI

设计中
